
export enum SoundNames {
  backgroundMusic2 = 'backgroundMusic2',
  fanfare = 'fanfare',
  buyMiner = 'buyMiner',
  buySlave = 'buySlave',
  buyFarmer = 'buyFarmer',
  buyBaker = 'buyBaker',
  buyMercator = 'buyMercator',
  buySmith = 'buySmith',
  buyLegionary = 'buyLegionary',
  buyPriest = 'buyPriest',
  buyForum = 'buyForum',
  closeModal = 'closeModal',
  click = 'click',
  coinClick = 'coinClick',
  upgrade = 'upgrade',
  buyFields = 'buyFields',
  levelUp = 'levelUp',
  gameOver = 'gameOver',
}

export const soundFiles = {
  [SoundNames.backgroundMusic2]: 'assets/audio/bgm2.mp3',
  [SoundNames.fanfare]: 'assets/audio/fanfare.mp3',
  [SoundNames.buyMiner]: 'assets/audio/buyMiner.mp3',
  [SoundNames.buySlave]: 'assets/audio/buySlave.mp3',
  [SoundNames.buyFarmer]: 'assets/audio/buyFarmer.mp3',
  [SoundNames.buyBaker]: 'assets/audio/buyBaker.mp3',
  [SoundNames.buyMercator]: 'assets/audio/buyMercator.mp3',
  [SoundNames.buySmith]: 'assets/audio/buySmith.mp3',
  [SoundNames.buyLegionary]: 'assets/audio/buyLegionary.mp3',
  [SoundNames.buyPriest]: 'assets/audio/buyPriest.mp3',
  [SoundNames.buyForum]: 'assets/audio/buyForum.mp3',
  [SoundNames.closeModal]: 'assets/audio/closeModal.mp3',
  [SoundNames.click]: 'assets/audio/click.mp3',
  [SoundNames.coinClick]: 'assets/audio/coin.mp3',
  [SoundNames.upgrade]: 'assets/audio/upgrade.mp3',
  [SoundNames.buyFields]: 'assets/audio/buyFields.mp3',
  [SoundNames.levelUp]: 'assets/audio/levelUp.mp3',
  [SoundNames.gameOver]: 'assets/audio/gameOver.mp3',
};
