/**
 * Skill icon spritesheet tunables.
 *
 * Sheets are generated by `scripts/build-skill-icon-spritesheets.py` into
 * `public/assets/skills/`, one per class per size, each laid out as a grid of
 * normal icons with an identical grid of disabled icons directly to its right.
 */

/** Sizes generated by the build script. Adding one means regenerating that size. */
export const SKILL_SHEET_SIZES = [32, 64, 102] as const;

export type SkillSheetSize = (typeof SKILL_SHEET_SIZES)[number];

/** Native cell size used when a component omits `sheetSize`. */
export const DEFAULT_SKILL_SHEET_SIZE: SkillSheetSize = 102;

/** One slug per generated sheet, matching the source pack's class folders. */
export const SKILL_SHEET_SLUGS = ['warrior-berserker', 'mage-sorcerer', 'archer-assassin', 'priest-paladin'] as const;

export type SkillSheetSlug = (typeof SKILL_SHEET_SLUGS)[number];

/**
 * Public URL of a generated sheet.
 *
 * The `indigolay-` prefix is load-bearing — `src/styles/utilities.css` keys the
 * `image-rendering: auto` opt-out off it.
 */
export function skillSheetUrl(slug: SkillSheetSlug, size: SkillSheetSize): string {
  return `/assets/skills/indigolay-skills-${slug}-${size}.png`;
}

/**
 * Sizes the asset service preloads. Sheets are large, so only the default size
 * is worth blocking the loader on; other sizes stream in when first rendered.
 */
export const PRELOADED_SKILL_SHEET_SIZES: readonly SkillSheetSize[] = [DEFAULT_SKILL_SHEET_SIZE];

/** Sheet URLs the asset service preloads. Spread into `assetList`. */
export const SKILL_ICON_SHEET_IMAGES: readonly string[] = PRELOADED_SKILL_SHEET_SIZES.flatMap((size) =>
  SKILL_SHEET_SLUGS.map((slug) => skillSheetUrl(slug, size)),
);

/** Geometry of one generated sheet. Mirrors the build script's `.json` manifest. */
export interface SkillSheetConfig {
  slug: SkillSheetSlug;
  cols: number;
  rows: number;
  /** Icons in the sheet. The tail of the last row can be empty. */
  iconCount: number;
}

/**
 * Grid geometry per sheet, transcribed from the manifests
 * `scripts/build-skill-icon-spritesheets.py` emits. Identical across the three
 * sizes — only the cell size changes — so it is stored once here rather than
 * per resolution.
 *
 * Rebuilding the sheets with a different `--cols` means updating these to match.
 */
export const SKILL_SHEETS = {
  'warrior-berserker': { slug: 'warrior-berserker', cols: 10, rows: 6, iconCount: 57 },
  'mage-sorcerer': { slug: 'mage-sorcerer', cols: 10, rows: 8, iconCount: 74 },
  'archer-assassin': { slug: 'archer-assassin', cols: 10, rows: 9, iconCount: 84 },
  'priest-paladin': { slug: 'priest-paladin', cols: 10, rows: 6, iconCount: 56 },
} as const satisfies Record<SkillSheetSlug, SkillSheetConfig>;
